#pragma warning( disable : 4482 )

#include<RDPony.h>

RDPony::RDPony(TextureStorage * ts)
{
	Energy = 100.0f;
	MaxEnergy = 100.0f;
	FillRate = 0.5f;
	flycost = 1.0f;  // skills by se nemìly nastavovat v konstruktoru
	candash = true;

	HUDa = ts->GetTexture(TextureStorage::TexName::RD_HUD_active);
	HUDi = ts->GetTexture(TextureStorage::TexName::RD_HUD_inactive);

	LPDIRECT3DTEXTURE9 ptex;

	IdleL = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_idle_left);
	IdleL->Add(new Sprite(ptex, true));

	IdleR = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_idle_right);
	IdleR->Add(new Sprite(ptex, true));

	WalkL = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_01);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_02);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_03);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_04);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_05);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_06);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_07);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_08);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_09);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_10);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_11);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_12);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_13);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_14);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_15);
	WalkL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_16);
	WalkL->Add(new Sprite(ptex, true));

	WalkR = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_01);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_02);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_03);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_04);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_05);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_06);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_07);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_08);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_09);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_10);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_11);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_12);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_13);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_14);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_15);
	WalkR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_16);
	WalkR->Add(new Sprite(ptex, true));

	FlyL = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_01);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_02);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_03);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_04);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_05);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_06);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_07);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_08);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_09);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_10);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_11);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_12);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_13);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_14);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_15);
	FlyL->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_left_16);
	FlyL->Add(new Sprite(ptex, true));

	FlyR = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_01);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_02);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_03);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_04);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_05);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_06);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_07);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_08);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_09);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_10);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_11);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_12);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_13);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_14);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_15);
	FlyR->Add(new Sprite(ptex, true));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_fly_right_16);
	FlyR->Add(new Sprite(ptex, true));

	JumpL = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_11);
	JumpL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_12);
	JumpL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_13);
	JumpL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_14);
	JumpL->Add(new Sprite(ptex, true));

	JumpR = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_11);
	JumpR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_12);
	JumpR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_13);
	JumpR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_14);
	JumpR->Add(new Sprite(ptex, true));

	FallL = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_left_14);
	FallL->Add(new Sprite(ptex, true));

	FallR = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_walk_right_14);
	FallR->Add(new Sprite(ptex, true));

	DashL = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_01);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_02);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_03);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_04);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_05);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_06);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_07);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_08);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_09);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_10);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_11);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_12);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_13);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_14);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_15);
	DashL->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_left_16);
	DashL->Add(new Sprite(ptex, true));

	DashR = new RoundList();
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_01);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_02);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_03);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_04);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_05);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_06);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_07);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_08);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_09);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_10);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_11);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_12);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_13);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_14);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_15);
	DashR->Add(new Sprite(ptex, false));
	ptex = ts->GetTexture(TextureStorage::TexName::RD_dash_right_16);
	DashR->Add(new Sprite(ptex, true));
}

void RDPony::GetTextures(TextureStorage * ts)
{
	HUDa = ts->GetTexture(TextureStorage::TexName::RD_HUD_active);
	HUDi = ts->GetTexture(TextureStorage::TexName::RD_HUD_inactive);

	Sprite * aux;

	IdleL->First->img = ts->GetTexture(TextureStorage::TexName::RD_idle_left);

	IdleR->First->img = ts->GetTexture(TextureStorage::TexName::RD_idle_right);

	aux = WalkL->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_01);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_02);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_03);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_04);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_05);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_06);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_07);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_08);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_09);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_10);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_14);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_15);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_16);

	aux = WalkR->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_01);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_02);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_03);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_04);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_05);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_06);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_07);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_08);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_09);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_10);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_14);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_15);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_16);

	aux = FlyL->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_01);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_02);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_03);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_04);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_05);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_06);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_07);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_08);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_09);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_10);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_14);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_15);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_left_16);

	aux = FlyR->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_01);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_02);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_03);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_04);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_05);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_06);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_07);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_08);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_09);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_10);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_14);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_15);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_fly_right_16);

	aux = JumpL->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_14);

	aux = JumpR->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_14);

	FallL->First->img = ts->GetTexture(TextureStorage::TexName::RD_walk_left_14);

	FallR->First->img = ts->GetTexture(TextureStorage::TexName::RD_walk_right_14);

	aux = DashL->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_01);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_02);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_03);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_04);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_05);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_06);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_07);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_08);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_09);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_10);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_14);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_15);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_left_16);

	aux = DashR->First;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_01);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_02);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_03);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_04);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_05);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_06);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_07);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_08);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_09);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_10);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_11);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_12);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_13);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_14);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_15);
	aux = aux->next;
	aux->img = ts->GetTexture(TextureStorage::TexName::RD_dash_right_16);
}